### ISSUE TITLE
lvmsurveysim faiiling

### ISSUE THREAD

**Issue by kslong** [sdss/lvmsurveysim#4]
When running the attached script in the current astroconda enviormement, lvmsurveysim is failing with these errors:

```
(astroconda) Pescado:surveydesign : python schedule_run.py 
Creating target list ...
Tiling Survey ...
Tiling target TileUnion MW
^[[1;13D   selecting tiles for THOR
   selecting tiles for MW2
   selecting tiles for MW1
Tiling target LMC
Tiling target SMC
Tiling target ORION
Tiling target ORION_SPARSE
Tiling target FULLSKY
LMC x FULLSKY Overlap loop exec time(s)= 0.749694
SMC x FULLSKY Overlap loop exec time(s)= 0.689748
ORION x ORION_SPARSE Overlap loop exec time(s)= 0.052306
ORION x FULLSKY Overlap loop exec time(s)= 0.744970
ORION_SPARSE x FULLSKY Overlap loop exec time(s)= 0.728171
MW1 x FULLSKY Overlap loop exec time(s)= 8.347681
MW2 x ORION_SPARSE Overlap loop exec time(s)= 0.847789
MW2 x FULLSKY Overlap loop exec time(s)= 10.708026
THOR x FULLSKY Overlap loop exec time(s)= 1.836569
Traceback (most recent call last):
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 3216, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: too many SQL variables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "schedule_run.py", line 73, in <module>
    run('./targets.yaml',tile=True,sim=False,plot=False,save=True)
  File "schedule_run.py", line 25, in run
    OpsDB.save_tiledb(tiledb) #, fits=True, path='lco_tiledb', overwrite=True)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/lvmsurveysim-0.8.3-py3.7.egg/lvmsurveysim/schedule/opsdb.py", line 220, in save_tiledb
    s = s2a.astropy2peewee(tile_table, Tile, replace=True)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/lvmsurveysim-0.8.3-py3.7.egg/lvmsurveysim/utils/sqlite2astropy.py", line 74, in astropy2peewee
    s = model.replace_many(table).execute()
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 1946, in inner
    return method(self, database, *args, **kwargs)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 2017, in execute
    return self._execute(database)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 2817, in _execute
    return super(Insert, self)._execute(database)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 2530, in _execute
    cursor = database.execute(self)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 3229, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 3223, in execute_sql
    self.commit()
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 2989, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/Users/long/anaconda3/envs/astroconda/lib/python3.7/site-packages/peewee-3.15.2-py3.7-macosx-10.9-x86_64.egg/peewee.py", line 3216, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: too many SQL variables
```
[z.Failure.220908.tar.gz](https://github.com/sdss/lvmsurveysim/files/9527959/z.Failure.220908.tar.gz)

One whould be able to run this modified version schedule_run.py as indicated above

Note also, that the script schedule_run.py that is in the repository has issues, specifically, as written

```
def run(targets='./targets.yaml', tile=False, sim=False, plot=False, save=False):
   # Creates a list of targets/
   print('Creating target list ...')
   targets = TargetList(target_file='./targets.yaml')
```
has an input of targets, but then the target file is hardwired.

**Comment by ndrory** [comment]
This is fixed by chunking the work on the databases.
